### ISSUE TITLE
PyTorch don't have tensor.shape

### ISSUE THREAD

**Issue by guixianjin** [wkentaro/pytorch-for-numpy-users#11]
maybe it should be tensor.size()

**Comment by wkentaro** [comment]
Maybe you're using an old version.

**Comment by guixianjin** [comment]
Okay, you are right. I check it in Pytroch 1.0.1. It really has tensor.shape. Thanks a lot. I'm a beginner of pytorch. I had checked the official tutorial and docs before, and I didn't find the usage of tensor.shape.
