### ISSUE TITLE
transpose and permute tests fail

### ISSUE THREAD

**Issue by elcorto** [wkentaro/pytorch-for-numpy-users#13]
```
_______________________________ test_numpy_0090 ________________________________

    def test_numpy_0090():
        x = np.array([[1, 2, 3], [4, 5, 6]])
>       x.transpose(2, 0, 1)
E       ValueError: axes don't match array

tests/test_numpy_0090.py:6: ValueError
______________________________ test_pytorch_0091 _______________________________

    def test_pytorch_0091():
        x = torch.tensor([[1, 2, 3], [4, 5, 6]])
>       x.permute(2, 0, 1); x.transpose(1, 2).tranpose(0, 1)  # 012 -> 021 -> 201
E       RuntimeError: number of dims don't match in permute

tests/test_pytorch_0091.py:6: RuntimeError
```
Seems like the tests assume to be operating on 3D arrays. Got this with numpy 1.17.4 and torch 1.5.0 .

**Comment by elcorto** [comment]
The changes that cause things to fail seem to have been added in f1d992d3b89eda8c352496733e3146aef1c4b4b6, confirmed by `git bisect`.

**Comment by elcorto** [comment]
Your recent CI runs pass, even though they should not. In fact they [do fail](https://github.com/wkentaro/pytorch-for-numpy-users/runs/726485871?check_suite_focus=true#step:6:206). The resason is a bug in `run_tests.py`: you call the pytest CLI from that script but swallow the exit code, so `run_tests.py` always exits 0.

PS: your CI job triggers on push, but does itself a push into master. Just wondering why that doesn't create a loop (note: I've never used GH actions so far). Thanks!

**Comment by wkentaro** [comment]
Thanks!
